spring.application.name=Task_Management_Project
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/Task-DB
spring.datasource.username=postgres
spring.datasource.password=Mrcom042497@psql


# JPA/Hibernate configuration. this persists data automatically to our DB's
# in production environment, set to none
spring.jpa.hibernate.ddl-auto=update
